### ISSUE TITLE
Добавление документации к проекту

### ISSUE THREAD

**Issue by dchudik** [HTMLProgrammer2001/messangerBack#1]
Приветствую! Добавьте пожалуйста документацию в ваш проект. Не очень удобно по коду ходить и смотреть где и какие параметры надо передавать в урлах.

**Comment by LizzVs** [comment]
Приветствую! Делаю на диплом - мессенджер на андроид и в качестве бекенд-части хотела бы использовать Ваш сервер(но не выдавать за свой!). Было бы здорово увидеть документацию к вашему проекту. Заранее спасибо.

**Comment by HTMLProgrammer2001** [comment]
Здравствуйте, хочу сразу предупредить, что в данном проекте используются сторонние сервисы: для отправки SMS сообщений https://developer.nexmo.com/, AWS SQS для отправки сообщений в веб-пуш и AWS S3 для хранения файлов. Вам либо придется зарегистрировать аккаунт в данных сервисах и поменять ключи доступа в настройках, либо заменить их на мок копии(я опишу как это сделать в доке). Если Вы всё равно хотите использовать мой бекенд, то я начну писать документацию.

**Comment by dchudik** [comment]
Добрый вечер! Это не пугает, функционал даже больше чем смог понять по коду. Супер! С удовольствием готовы увидеть документацию и использовать Ваши наработки. Заранее спасибо)

**Comment by LizzVs** [comment]
Спасибо за ответ! Ничего страшного, заодно изучу новые сервисы)

**Comment by HTMLProgrammer2001** [comment]
https://drive.google.com/file/d/1MzutPwYLezfeV0q2PlPNMBQ8q_62OpnV/view?usp=sharing
